@echo off
:a
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.youtube.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.google.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
start www.w3resource.com
goto :a